Feat/modal
milealmeida/side-project-pokemon pull request #12
Opened 2023-04-07 01:35 UTC by milealmeida

2023-04-17 23:02 UTC, Claytonrss requested changes

2023-04-17 23:02 UTC, Claytonrss commented on public/img/who.png
Pode fazer um compress em geral nas imagens que vao ficar dentro do projeto para ganhar mais performance

![image](https://user-images.githubusercontent.com/33030911/232621293-d62bbb0e-d5c6-4307-947f-86c2aed55e1e.png)

Pode utilizar o https://tinypng.com/

2023-04-17 23:02 UTC, Claytonrss commented on src/components/organisms/Modal/index.tsx
> +  height: number | null | undefined;
Aqui seria melhor declarar a props como opcional

2023-04-18 00:07 UTC, milealmeida commented on public/img/who.png
Feito

2023-04-18 00:08 UTC, milealmeida commented on src/components/organisms/Modal/index.tsx
> +  height: number | null | undefined;
Nossa, eu tinha esquecido disso kkkkkk

2023-04-18 00:55 UTC, Claytonrss approved these changes

2023-04-18 13:30 UTC, merged