[Feat] Create Card Pokemon
milealmeida/side-project-pokemon pull request #4
Opened 2022-12-20 17:23 UTC by milealmeida

2022-12-20 23:43 UTC, iamdevmarcos approved these changes

2022-12-20 23:45 UTC, iamdevmarcos commented
@milealmeida Fiz algumas alteracoes, e sugestoes pra voce nesse commit aqui:
https://github.com/milealmeida/side-project-pokemon/pull/4/files

Qualquer coisa é só avisar 🧐

2022-12-20 23:51 UTC, iamdevmarcos commented
Link da documentacao do utilitario Record do Typescript.
https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type
https://stackoverflow.com/questions/51936369/what-is-the-record-type

2022-12-21 00:47 UTC, Claytonrss requested changes

2022-12-21 00:47 UTC, Claytonrss commented on src/components/organisms/Card/index.tsx
> +        {type2 && <Type type={type2} />}
Acho que pode ficar legal trabalhar com um array de types, ao invés de duas variáveis type e type2.
Isso pode facilitar para quando vc estiver trabalhando com a API tbm

2022-12-21 23:42 UTC, Claytonrss approved these changes

2022-12-21 23:45 UTC, merged