[Feat] Pokemon API integration with Graphql
milealmeida/side-project-pokemon pull request #6
Opened 2022-12-28 20:11 UTC by milealmeida

2022-12-28 22:13 UTC, Claytonrss requested changes

2022-12-28 22:13 UTC, Claytonrss commented on src/Templates/Home/index.tsx
> +import { PokemonsProps } from './sections/Pokemons';
Como esse tipo é utilizado por toda aplicacao, acho que pode ser legal deixar ele na pasta src/types

2022-12-28 22:13 UTC, Claytonrss commented on src/Templates/Home/sections/Pokemons/index.tsx
> +import { SamplePokeApIqueryQueryResult } from 'generated/graphql';
Acho que pode ser legal renomear esse tipo
Ele pegou esse nome pq foi usado no nome da query GraphQL

2022-12-29 20:54 UTC, milealmeida commented on src/Templates/Home/index.tsx
> +import { PokemonsProps } from './sections/Pokemons';
Movido

2022-12-29 20:54 UTC, milealmeida commented on src/Templates/Home/sections/Pokemons/index.tsx
> +import { SamplePokeApIqueryQueryResult } from 'generated/graphql';
Alterado (yarn codegen resolveu)

2022-12-29 22:11 UTC, Claytonrss approved these changes

2022-12-30 23:48 UTC, merged